[package]
name = "browser-from-scratch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = {version= "0.3.0", features=["canvas"] }
reqwest = {version ="0.11.6",features=["blocking"]}